dist:     trusty
sudo:     required

language: cpp

os:
    - linux
#    - osx

compiler:
    - gcc
#    - clang

env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
#    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
#    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
#    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
    exclude:
        - os:       osx
          compiler: gcc

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
    - source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
    - mkdir build
    - cd build
    - export QT_BASE_DIR=/opt/qt59
    - export QTDIR=$QT_BASE_DIR
    - export PATH=$QT_BASE_DIR/bin:$PATH
    - export LD_LIBRARY_PATH=$QT_BASE_DIR/lib/x86_64-linux-gnu:$QT_BASE_DIR/lib:$LD_LIBRARY_PATH
    - export PKG_CONFIG_PATH=$QT_BASE_DIR/lib/pkgconfig:$PKG_CONFIG_PATH
    - $CMAKE_DIR/bin/cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - $CMAKE_DIR/bin/cmake --build . --target all
#    - ctest --output-on-failure
